#version: "3.8"
#
#services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql-db
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: web_banquanao
#    volumes:
#      - mysql-data:/var/lib/mysql
#    networks:
#      - app-network
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: webbanquanao
#    depends_on:
#      mysql:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/web_banquanao
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
#      SERVER_PORT: 8080
#      SERVER_ADDRESS: 0.0.0.0
#    ports:
#      - "8080:8080"
#    networks:
#      - app-network
#
#volumes:
#  mysql-data:
#
#networks:
#  app-network:
